### ISSUE TITLE
602: Source Query (All Properties) rejects transformed posts

### ISSUE THREAD

**Issue by myfreeweb** [aaronpk/micropub.rocks#70]
micropub.rocks posts this:

```json
{
  "type": ["h-entry"],
  "properties": {
    "content": ["Test of querying the endpoint for the source content"],
    "category": ["micropub", "test"]
  }
```

However, my server returns this:

```json

{
    "children": null,
    "deleted": false,
    "type": [
        "h-entry"
    ],
    "acl": [
        "*"
    ],
    "properties": {
        "category": [
            "_notes",
            "micropub",
            "test"
        ],
        "published": [
            "2017-05-14T19:24:53.890888443Z"
        ],
        "url": [
            "https://unrelenting.technology/notes/2017-05-14-19-24-53"
        ],
        "content": [
            {
                "html": "<p>Test of querying the endpoint for the source content</p>\n"
            }
        ],
        "updated": [
            "2017-05-14T19:24:53.890888443Z"
        ],
        "client-id": [
            "https://micropub.rocks/"
        ]
    }
}
```

The content has been rendered as markdown to html, and the `_notes` category has been added because there were no categories beginning with `_` — that's the internal logic of my server. I think micropub.rocks should tolerate that and only check that `micropub` and `test` are *included* as categories, and that some value under `content` *contains* the original text. 

https://micropub.rocks/implementation-reports/servers/86/ZKniYHa9uPsdIbAuW0Em

**Comment by myfreeweb** [comment]
Oh also the same happens with `802: Does not store access token property`

**Comment by aaronpk** [comment]
The test currently does check that `category` contains the specified categories and allows additional categories to be added. 

However, I'm not convinced that returning transformed content is the correct thing to do. Part of the reason the test checks for an exact match of the content is to be able to have clients more easily support editing the content. If a client creates a post with content `Hello World`, and then wants to load that post into the editing interface, it wouldn't know what to do when the Micropub endpoint returns `{"html":"<p>Hello World</p>"}` for the content.

I think the Micropub endpoint should store the source content as the user entered it, so that clients can rely on being able to edit the post without understanding any transformations that may have occurred.

Imagine a slightly more complex example, where you create a post with some actual markdown content: 

```
## Post Title

This is a list of my favorite colors.

* Red
* Green
* Blue
```

Now imagine you want to later edit this post. Would you rather be editing the Markdown content or the transformed HTML? I would imagine you'd want to edit the Markdown content. This is why the Micropub endpoint should return the exact contents entered by the user.

**Comment by myfreeweb** [comment]
Yeah I have been considering moving the markdown processing from the micropub side to the html templating side…
